kind: Pod
apiVersion: v1
metadata:
  name: local-pvc-pod3
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "echo Hello Pod Three &&  sleep 3600"]
    volumeMounts:
    - mountPath: "/data"
      name: local-volume3
  volumes:
  - name: local-volume3
    persistentVolumeClaim:
      claimName: local-pvc3
